[NOTE]
====
Short summary about company and latest product/development - few bullet points.

Website: link:http://yarenty.com[]
====

Extract from website(or internet news) - latest product details, ie:

- hardware description,
- software capabilities,
- benchmarking - MLPerf output.

Mostly about latest development - latest chip, or latest version of software - at the end this is all about technology trends not full history of each company.


[IMPORTANT]
.Note from Jaro
====
Third seciton is ... note from me ;-) - short investigation about what was going on lately in the company, ie: last year activity /development / are they growing or stagnating.

====



Mobile
AMD: Energy efficiency improvement dominates micro-architecture + processor architecture innovation to promote the overall performance of Renior


2014: Increase the energy efficiency of mobile processors by 25 in 2020
2020: "Renior" completes 31x energy efficiency improvement, the processor is mainly used for ultra-thin notebooks; 5x performance improvement, 84% lower energy consumption


Zen2 CPU micro-architecture optimization
15% IPC improvement compared to Zen; hierarchical cache optimization for Renior; each Renior Die has two Zen2 cores
VEGA GPU maximizes the efficiency of each processing unit
25% increase in peak graphics clock + 77% increase in peak memory bandwidth; 2x data interface
Two memory controllers
Infinity fabric
75% better energy efficiency; 77% higher memory bandwidth



Intelligent low-power state selection
Increase in power consumption status exposed to ACPI: 1 -> 3
Optimize the duration and depth of each state

Optimize battery life
SoC power consumption reduced by 20%
Low power state management and efficiency improvement

Closed loop "thermal" management system
Hot spot temperature sensing
The temperature information is transmitted to the infinity fabric through the embedded controller
The system dynamically adjusts the power consumption limit according to the external temperature information of the machine
